### ISSUE TITLE
link to nbviewer

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/timeseries-analysis-example#1]
I suggest to add a link to NB viewer in the README, along the lines of [NBViewer: IonBindingAnalysis.ipynb](http://nbviewer.ipython.org/github/Becksteinlab/timeseries-analysis-example/blob/master/IonBindingAnalysis.ipynb) so that one can immediately look at the notebook.

**Comment by dotsdl** [comment]
Good point! I'll add it now.

**Comment by dotsdl** [comment]
Fixed in 57b276689d877cb2cb7077b86f5277cd0936aeb8
